backend:
  name: github
  repo: <your-github-username>/drekoria.com
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "data/site.json"
        label: "Site Data"
        name: "site"
        fields:
          - label: "Navigation Links"
            name: "nav_links"
            widget: list
            fields:
              - {label: "Label", name: label, widget: string}
              - {label: "URL", name: url, widget: string}
          - label: "Home Page"
            name: index
            widget: object
            fields:
              - {label: "Hero Title", name: hero_title, widget: string}
              - {label: "Hero Text", name: hero_text, widget: text}
          - label: "World Page"
            name: world
            widget: object
            fields:
              - {label: "Hero Title", name: hero_title, widget: string}
              - {label: "Hero Text", name: hero_text, widget: text}
          - label: "Characters Page"
            name: characters
            widget: object
            fields:
              - {label: "Hero Title", name: hero_title, widget: string}
              - {label: "Hero Text", name: hero_text, widget: text}
          - label: "Podcast Page"
            name: podcast
            widget: object
            fields:
              - {label: "Chronicles Title", name: chronicles_title, widget: string}
              - {label: "Chronicles Text", name: chronicles_text, widget: text}
              - {label: "Voice Title", name: voice_title, widget: string}
              - {label: "Voice Text", name: voice_text, widget: text}
